export default {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  ignoreFiles: ['**/dist*/**', '**/node_modules/**'],
  rules: {
    'selector-class-pattern': [
      '^[a-z][a-z0-9]*(?:-[a-z0-9]+)*(?:__[a-z0-9]+(?:-[a-z0-9]+)*)?(?:--[a-z0-9]+(?:-[a-z0-9]+)*)?$',
      {
        message: 'Use BEM: block, block__element or block--modifier',
        resolveNestedSelectors: true,
      },
    ],
    'declaration-empty-line-before': 'never',
    'alpha-value-notation': null,
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'color-hex-length': null,
    'custom-property-empty-line-before': null,
    'media-feature-range-notation': null,
    'property-no-deprecated': null,
    'rule-empty-line-before': ['always', { except: ['after-single-line-comment', 'first-nested'] }],
    'scss/at-rule-no-unknown': true,
    'scss/dollar-variable-empty-line-before': null,
    'selector-not-notation': null,
    'shorthand-property-no-redundant-values': null,
    'value-keyword-case': null,
    'order/order': [
      'custom-properties',
      'dollar-variables',
      { type: 'at-rule', name: 'include' },
      'declarations',
      'rules',
      { type: 'at-rule', name: 'media' },
    ],
    'order/properties-order': [
      'content',
      'position',
      'inset',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'visibility',
      'float',
      'clear',
      'isolation',
      'overflow',
      'overflow-x',
      'overflow-y',
      'box-sizing',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'grid',
      'grid-template',
      'grid-template-columns',
      'grid-template-rows',
      'grid-row',
      'grid-column',
      'grid-area',
      'place-items',
      'place-content',
      'align-items',
      'align-content',
      'align-self',
      'justify-items',
      'justify-content',
      'justify-self',
      'gap',
      'row-gap',
      'column-gap',
      'flex',
      'flex-flow',
      'flex-direction',
      'flex-wrap',
      'flex-grow',
      'flex-shrink',
      'order',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-radius',
      'outline',
      'outline-offset',
      'background',
      'background-color',
      'background-image',
      'box-shadow',
      'opacity',
      'color',
      'font',
      'font-family',
      'font-size',
      'font-weight',
      'font-style',
      'line-height',
      'letter-spacing',
      'text-align',
      'text-decoration',
      'text-transform',
      'text-overflow',
      'white-space',
      'object-fit',
      'object-position',
      'clip',
      'clip-path',
      'transform',
      'transform-origin',
      'transition',
      'animation',
      'cursor',
      'pointer-events',
      'touch-action',
      'user-select',
      'will-change',
      'backface-visibility',
    ],
  },
};
